### ISSUE TITLE
Folder hierarchy

### ISSUE THREAD

**Issue by KfirdausMT** [furkanulger/Anomaly-detection-for-solder#1]
I see in your readme.md the folder hierarchy is like below: 
    .
    ├── dataset                   
    │   ├── train 
    │   ├── validation        
    │   └── test    
    │        ├── normal
    │        ├── anomaly
    │            ├──image1.png
    │            ├──image2.png

Seems like your train and validation folder dont have any subfolder. How you able to load train and validation dataset using datasets.ImageFolder in dataloader.py as it dont have any class? I've tried and it prompted error "Couldn't find any class folder in dataset/train"

**Comment by furkanulger** [comment]
Train and validation folders should also have subfolders namely, normal and anomaly as in test. I did not add them explicitly to keep the scheme concise. Once you create the subfolders under train and validation with normal and anomaly subfolders, you will be able to load your data.
